resource_group_name: "rg-aks-__ENV__-__LOCATION__"

vnet:
  address_space: ["__ADDRESS_SPACE__"]
  subnets:
    - key: "aks-nodes"
      name: "snet-aks-nodes"
      cidrs: ["__AKS_SUBNET_CIDR__"]

user_managed_identities:
  kubelet:
    name: "__KUBELET_IDENTITY_NAME__"
  controlplane:
    name: "__CONTROLPLANE_IDENTITY_NAME__"
