identities:
  dns:
    name: "dns-zone-__ENV__-__LOCATION__"
    resource_group_name: "rg-network-__ENV__-__LOCATION__"
    role_definition_name: "Private DNS Zone Contributor"
    scope_resource_id: "/subscriptions/{{ cookiecutter.subscription_id }}/resourceGroups/rg-network-__ENV__-__LOCATION__/providers/Microsoft.Network/privateDnsZones/{{ cookiecutter.client_name }}.internal"
    federated_credentials_advanced:
      external-dns:
        name: "dns-zone-__ENV__-__LOCATION__-external-dns"
        subject_identifier: "system:serviceaccount:external-dns:external-dns-sa"

  eso:
    name: "kv-eso-__ENV__-__LOCATION__"
    resource_group_name: "rg-managed-__ENV__-__LOCATION__"
    role_definition_name: "Key Vault Secrets User"
    scope_resource_id: "/subscriptions/{{ cookiecutter.subscription_id }}/resourceGroups/rg-managed-__ENV__-__LOCATION__/providers/Microsoft.KeyVault/vaults/kv-{{ cookiecutter.client_name }}-__ENV__-__LOCATION_SHORT__"
    federated_credentials_advanced:
      eso:
        name: "kv-eso-__ENV__-__LOCATION__-eso"
        subject_identifier: "system:serviceaccount:external-secrets-operator:external-secrets-operator-sa"

  loki:
    name: "loki-__ENV__-__LOCATION__"
    resource_group_name: "rg-managed-__ENV__-__LOCATION__"
    role_definition_name: "Storage Blob Data Contributor"
    scope_resource_id: "/subscriptions/{{ cookiecutter.subscription_id }}/resourceGroups/rg-managed-__ENV__-__LOCATION__/providers/Microsoft.Storage/storageAccounts/st{{ cookiecutter.client_name }}__ENV____LOCATION_SHORT__"
    federated_credentials_advanced:
      loki:
        name: "loki-__ENV__-__LOCATION__-loki"
        subject_identifier: "system:serviceaccount:monitoring:loki-sa"

  tempo:
    name: "tempo-__ENV__-__LOCATION__"
    resource_group_name: "rg-managed-__ENV__-__LOCATION__"
    role_definition_name: "Storage Blob Data Contributor"
    scope_resource_id: "/subscriptions/{{ cookiecutter.subscription_id }}/resourceGroups/rg-managed-__ENV__-__LOCATION__/providers/Microsoft.Storage/storageAccounts/st{{ cookiecutter.client_name }}__ENV____LOCATION_SHORT__"
    federated_credentials_advanced:
      tempo:
        name: "tempo-__ENV__-__LOCATION__-tempo"
        subject_identifier: "system:serviceaccount:monitoring:tempo-sa"
