postfix: "{{ cookiecutter.client_name }}"
resource_group_name: "rg-managed-__ENV__-__LOCATION_SHORT__"

administrator_login:    "__POSTGRES_ADMIN_LOGIN__"
administrator_password: "CHANGE_ME"

sku_name:           "__POSTGRES_SKU__"
postgresql_version: "__POSTGRES_VERSION__"
storage_mb:         __POSTGRES_STORAGE_MB__
zone:               __POSTGRES_ZONE__

databases:
  app:
    name:    "__POSTGRES_DB_NAME__"
    charset: "UTF8"
